name: Publish Swift Package (on tag)

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v0.1.0, v1.2.3

permissions:
  contents: write   # needed to create the release

jobs:
  build-and-test:
    name: Build & Test (SPM)
    runs-on: macos-14
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Select Xcode (latest)
        run: |
          sudo xcode-select -s "/Applications/Xcode.app"
          xcodebuild -version

      - name: Swift version
        run: swift --version

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build (debug)
        run: swift build --build-tests

      - name: Run tests
        run: swift test --parallel

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Extract tag
        id: tag
        run: echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: ${{ steps.tag.outputs.TAG }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Trigger Swift Package Index builds if you add SPI_TOKEN as a repo secret
  trigger-swift-package-index:
    name: Trigger Swift Package Index (optional)
    runs-on: ubuntu-latest
    needs: create-release
    if: ${{ secrets.SPI_TOKEN != '' }}
    steps:
      - name: Call SPI build trigger API
        run: |
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          curl -sS -X POST \
            -H "Authorization: Bearer ${{ secrets.SPI_TOKEN }}" \
            https://swiftpackageindex.com/api/packages/$OWNER/$REPO/trigger-builds \
            -d '{"parameters": {"version": "'"${GITHUB_REF_NAME}"'"}}' \
          || echo "SPI trigger call failed (token missing or API unavailable)."